apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
  namespace: pythonsun
spec:
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python-django
        image: swamy877/python_django_new:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
